### ISSUE TITLE
Update URL as map state changes

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#100]
Might be cool to make updates to the map as people navigate it, especially since I already set up the page to accept lat/lon/address parameters.

(ties back to #42)

**Comment by jkeefe** [comment]
Seconded! Really useful to be able to send reporters links -- or tweet them out -- that resolve to the lat-lon I searched.

**Comment by JoeGermuska** [comment]
I opted out of tracking map view state: zoom, center, highlighted layers -- but it does manage the state every time the point-of-interest is changed (address search or double-click-on-map)
