### ISSUE TITLE
Some Tiger2013 provided GeoJSON files do not load into R's readOGR().

### ISSUE THREAD

**Issue by vielmetti** [censusreporter/censusreporter#102]
I'm using R and the readOGR() tool provided by the rgdal package, docs here:

http://www.inside-r.org/packages/cran/rgdal/docs/ogrInfo

When I load in some of the GeoJSON files provided by the Census Reporter, the files are not recognized as valid geometry by the "rgeos" package's "gIsValid" check.

http://www.inside-r.org/packages/cran/rgeos/docs/gIsValid

```
> library(rgeos)
> library(rgdal)
> Z=readOGR("http://api.censusreporter.org/1.0/geo/show/tiger2013?geo_ids=05000US23003","OGRGeoJSON")
OGR data source with driver: GeoJSON 
Source: "http://api.censusreporter.org/1.0/geo/show/tiger2013?geo_ids=05000US23003", layer: "OGRGeoJSON"
with 1 features and 2 fields
Feature type: wkbMultiPolygon with 2 dimensions
> gIsValid(Z)
[1] FALSE
Warning message:
In RGEOSUnaryPredFunc(spgeom, byid, "rgeos_isvalid") :
  Self-intersection at or near point -69.04874805339054 47.424261813674015
```

Here's a reference for a polygon self-intersection check algorithm, for reference:

http://engblog.nextdoor.com/post/86430627239/fast-polygon-self-intersection-detection-in

**Comment by vielmetti** [comment]
and for completeness, an answer to my own question: I get the file to load after one more processing step in R to remove self-intersections.

```
> gIsValid(Z)
[1] FALSE
Warning message:
In RGEOSUnaryPredFunc(spgeom, byid, "rgeos_isvalid") :
  Self-intersection at or near point -69.04874805339054 47.424261813674015
> gIsValid(gBuffer(Z, width=0.0))
[1] TRUE
Warning message:
In gBuffer(Z, width = 0) :
  Spatial object is not projected; GEOS expects planar coordinates
```

I tried to fix through a preprocessing step with ogr2ogr but couldn't find an incantation that did the right thing.

**Comment by JoeGermuska** [comment]
@iandees would this be fixed just by replacing all cases of `ST_Simplify` with `ST_SimplifyPreserveTopology` in [api.py](https://github.com/censusreporter/census-api/blob/master/census_extractomatic/api.py)?

**Comment by iandees** [comment]
@JoeGermuska maybe. We should definitely try it, but I think the data from Census is just invalid (self-intersecting) in some cases. If the `ST_SimplifyPreserveTopology` change doesn't solve it we could try adding in [`ST_MakeValid`](http://postgis.net/docs/ST_MakeValid.html).

**Comment by JoeGermuska** [comment]
>Warning in install.packages :
  package ‘rgdal’ is not available (for R version 3.1.2)

so I can't really test this @vielmetti but I implemented the`ST_SimplifyPreserveTopology` fix. Can you see if it's different?

**Comment by vielmetti** [comment]
Looks like it works fine now.

```
> Z=readOGR("http://api.censusreporter.org/1.0/geo/show/tiger2013?geo_ids=05000US23003","OGRGeoJSON")
OGR data source with driver: GeoJSON 
Source: "http://api.censusreporter.org/1.0/geo/show/tiger2013?geo_ids=05000US23003", layer: "OGRGeoJSON"
with 1 features and 2 fields
Feature type: wkbPolygon with 2 dimensions
> gIsValid(Z)
[1] TRUE
```

Thanks!

**Comment by vielmetti** [comment]
I'm going to give this a more exhaustive test this evening, but I'm closing this now and I'll reopen it if I get another test case.

**Comment by vielmetti** [comment]
Ran about 2900 test cases without a hitch - thanks!

**Comment by vielmetti** [comment]
For completeness, here's a writeup of my pipeline:

http://vielmetti.typepad.com/vacuum/2015/03/cleaning-polygons-in-r-and-shapely.html

**Comment by vielmetti** [comment]
and for what it's worth, what I'm attempting to do is get a clean geometry that's a union of the provided results (so one polygon that's the sum of all of the counties returned, rather than a set of polygons). If it's not too slow to implement, that would be a nice option.
