### ISSUE TITLE
Geographies are missing for some old county FIPS codes and for territory FIPS codes

### ISSUE THREAD

**Issue by vielmetti** [censusreporter/censusreporter#103]
This is a list of county FIPS geographies where I have a FIPS code but the Census Reporter geo tool does not have a GeoJSON file. I don't know if it's a comprehensive list.

At least one of these (the Skagway-Hoonah-Angoon, AK code 02232) represents an old geography that was present in an older census but that is not in the current release. 

AS is American Samoa, GU is Guam, VI is Virgin Islands. 

http://api.censusreporter.org/1.0/geo/show/tiger2013?geo_ids=05000US02232 shows the problem. (Is there some other geo endpoint that I can hit that might have these GeoJSON coordinates in it?)

```
05000US02232,"AK, Skagway-Hoonah-Angoon"
05000US02280,"AK, Wrangell-Petersburg"
05000US60000,"AS, Eastern"
05000US60030,"AS, Rose Island"
05000US60040,"AS, Swains Island"
05000US60050,"AS, Western"
05000US66010,"GU, Guam"
05000US78010,"VI, Angaur"
05000US78010,"VI, St. Croix"
05000US78020,"VI, St. John"
05000US78030,"VI, St. Thomas"
```

thanks!

Ed

**Comment by JoeGermuska** [comment]
Those Alaskan counties are no longer in TIGER (the gazetteers are a cool way to check that kind of thing https://www.census.gov/geo/maps-data/data/gazetteer2013.html).

The Island areas aren't in the ACS, so we skip those (see #104 for more), as we considered the GIS API as a service mostly for CensusReporter. Seeing that it has broader general use, we might reconsider, but for now, that's the explanation.

**Comment by JoeGermuska** [comment]
Reviewing tickets, I'm going to close this and let #104 serve as the focal point for these issues.

**Comment by ShekharSahu** [comment]
Why do `05000US78010,"VI, Angaur"` and `05000US78010,"VI, St. Croix"` have same fips code?
