### ISSUE TITLE
feature request: return unioned polygons as option in geojson interface

### ISSUE THREAD

**Issue by vielmetti** [censusreporter/censusreporter#105]
For motivation and some algorithms, see http://vielmetti.typepad.com/vacuum/2015/03/cleaning-polygons-in-r-and-shapely.html

Right now, if you go through the API for geo/show and request a set of geo_ids like so

http://api.censusreporter.org/1.0/geo/show/tiger2013?geo_ids=05000US23003,05000US23009,05000US23019,05000US23021,05000US23027,05000US23029

you get a GeoJSON file back that has multiple polygons. If instead you want a unified area that's the union of all of those areas, you have to merge them together yourself.

It should be possible to put that merge step as an option into the API, and have the database do the geo-merging by itself. The routines I use all end up calling GEOS to do the work, so those are all available via http://postgis.net/docs/reference.html#Geometry_Processing . 

Getting it absolutely right for any arbitrary merged geometry might be hard, but I don't think it would be slow. (It has to be faster to do it in the database than to do it in R!)

**Comment by iandees** [comment]
I feel that doing this kind of GIS work in the API is out of the scope of our API. It might make sense if we offered Census data unioned across arbitrary geographies, but we don't currently.

**Comment by JoeGermuska** [comment]
I agree with @iandees -- while I would love to support more diverse ways of using the data, this is out of scope.

**Comment by vielmetti** [comment]
Thanks! Sounds like the right decision.
