### ISSUE TITLE
American FactFinder Links broken

### ISSUE THREAD

**Issue by alexandersimoes** [censusreporter/censusreporter#106]
Seems like none of these links are working -- http://censusreporter.org/topics/table-codes/

**Comment by JoeGermuska** [comment]
Could you be more specific? I tried several wih no obvious errors.

**Comment by alexandersimoes** [comment]
Ya sorry! All of the links to the american factfinder site were returning a Java error, thought maybe the links were malformed but they seem to be working fine now... :-/ weird.
