### ISSUE TITLE
Choropleth: improve legend for Gini index maps

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#107]
A user reported via [UserVoice (#94)](https://censusreporter.uservoice.com/admin/tickets/94/) that the labels on the choropleth for Gini Index e.g. [States in US map](http://censusreporter.org/data/map/?table=B19083&geo_ids=040|01000US&primary_geo_id=01000US) should have a couple of digits of decimals since the number ranges from 0-1.

This is quite correct. 

![Screenshot of legend](https://s3.amazonaws.com/uploads.uservoice.com/assets/078/186/811/medium/Screenshot-MaihBN0avryKYvcabJ4gWt8h53rbxCvkHjEQq3S6WlT5RfX0FW1427717382060.png?AWSAccessKeyId=14D6VH0N6B73PJ6VE382&Expires=1427756756&Signature=TaBDeM0%2FaOsmTrna2WEqhIq%2FSjQ%3D)

**Comment by JoeGermuska** [comment]
Follow-up from original reporter:

> Doesn't appear to be a bucketing problem. Looks like a numerical  precision display problem that might fit a general case:
> 
> Table & Distribution views of same data handle it well. State range is  0.4083 to 0.5320. Pulling the data into google fusion where I have  control of the ranges, it looks like your buckets are good.
> 
> states:  http://censusreporter.org/data/map/?table=B19083&geo_ids=040|01000US,040|01000US&primary_geo_id=01000US  google fusion map: http://goo.gl/xYANLZ  atlanta zips:  http://censusreporter.org/data/map/?table=B19083&geo_ids=16000US1304000,860|16000US1304000,140|16000US1304000&primary_geo_id=16000US1304000#column|B19083001,sumlev|860

**Comment by JoeGermuska** [comment]
@ryanpitts this seems like it would be pretty simple, if you have some spare cycles

**Comment by ryanpitts** [comment]
:+1:

**Comment by ryanpitts** [comment]
![screen shot 2015-05-03 at 11 33 16 am](https://cloud.githubusercontent.com/assets/56477/7446284/472ff718-f188-11e4-9575-b408cc0c4933.png)
