### ISSUE TITLE
scroll-to-zoom for 'map' data view?

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#114]
A [UserVoice](https://censusreporter.uservoice.com/admin/tickets/103) comment on [a 'map' data view page](http://censusreporter.org/data/map/?table=B19001&geo_ids=140|31000US47900#column|B19001009,sumlev|140) said:

> Hi! I can't zoom in using my mouse; that makes it difficult to look at a particular census tract without accidentally clicking on another census tract.

My response:

> We chose to disable scroll-wheel zooming because there are other pages on Census Reporter where the likelihood of accidentally zooming the map when you were actually trying to move down the page was higher and we didn't want users to be frustrated.
> 
> Note that there are zoom controls in the upper right corner of the map.
> 
> For the map/data view from which you sent this feedback, admittedly there is no other scrolling, so allowing scroll-wheel-zooming might be worth turning on. We'll consider whether that inconsistency is minor and possibly enable it.
> 
> Thanks for the input.

should we enable scroll-to-zoom for this page alone?

**Comment by ryanpitts** [comment]
I vote no. Not just because of the inconsistency it would introduce -- I also think the UX drawbacks of accidental scroll-wheel-zooming are much greater than the benefits of intentional use, especially when there's an alternate zoom control on the page.

**Comment by iandees** [comment]
I was going to vote no as well, but I think that it might be more important to allow scroll-zooming when the map consumes the whole page like in this example. It definitely doesn't make sense to allow scroll-zooming when the map is just the header of the profile page, for example.

That being said, I think the zoom controls solve the problem pretty well.

**Comment by JoeGermuska** [comment]
the nos have it
