### ISSUE TITLE
Add a suggested citation form for crediting data

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#118]
A [UserVoice ticket](https://censusreporter.uservoice.com/admin/tickets/104/) said:
> Students would love you if you put a citation for your cite at the bottom of your page!

This is a good idea.

**Comment by JoeGermuska** [comment]
This came up again. It's so easy, let's knock it out.

I'm going to start by saying we should base it off of the form presented at http://libguides.usc.edu/c.php?g=235185&p=1560630

For data table pages:
U.S. Census Bureau (_data_release_year_). _Table name_, (ACS Year or Years) American Community Survey (1 or 5)-year estimates. Retrieved from <census reporter url>.

For profile pages:
U.S. Census Bureau (_data_release_year_). (ACS Year or Years) American Community Survey (1 or 5)-year estimates. Retrieved from _ Census Reporter Profile page for [place name]_ <census reporter url>.

I started a couple steps towards this on the `citation` branch. Issues:

profile pages sometimes have data from two releases. It would be nice to present both citation forms if (and only if) they are necessary.

We don't have structured access to the release year. We could maybe put it in to `ACS_RELEASES` in `utils.py` along with the "ACS Year or Years" part needed for the template above, although I see that we never added acs2014_5yr to that so it must not be used much. I guess we sorta trust the API data for citations, but putting all this over there seems like the wrong spot.

Anyway, gotta put this down for today.

**Comment by ryanpitts** [comment]
@JoeGermuska working on the data table pages in https://github.com/censusreporter/censusreporter/commit/c383a28a2e0586b1a018284cf7649cca6d3baee2 

Can't fill in the appropriate data for a citation until Comparison() gets run, since that's where we're hitting the API. So seemed like we needed to be able to pass an optional callback into Comparison, like https://github.com/censusreporter/censusreporter/commit/c383a28a2e0586b1a018284cf7649cca6d3baee2#diff-9fa68e886ffd1d228a1117a5e3180515L62

If you've got any more elegant ways of doing this, I'm all ears. Kind of hate not being able to just take care of it all right in the page template.

**Comment by ryanpitts** [comment]
Oh, also the citation line is added to `_base_data.html`, so it shows up on the table and distribution charts. Currently it _doesn't_ show on the map view, because the map does its full-screen thing. Do you think we need the line on the map page too?

**Comment by JoeGermuska** [comment]
I think we can live without putting it on the map.

**Comment by ryanpitts** [comment]
I thought briefly about trying to tuck it into the box that holds the controls on the map page, but that feels like a lot of clutter there for _very_ infrequent gain. Can't imagine a lot of cites coming directly off the map view.

**Comment by JoeGermuska** [comment]
@ryanpitts  Do you think there's a way to get the profile page citation to be more specific about which ACS the data comes from? I know that on the page as a whole, there's a chance that it comes from more than one, so it would be ugly -- but the citation we have right now seems a little incomplete.

I guess my main thought would be identifying which releases are present on the page and then showing as many citations as necessary, with some explanatory text for cases where there is more than one relevant to the page?

**Comment by ryanpitts** [comment]
OK, just pushed an update to profile page citations: https://github.com/censusreporter/censusreporter/commit/f75ec8874f0cd4afa7ebeb84f25e3927576252f1

If a page uses more than one release, now looks like:

![screen shot 2016-03-06 at 6 09 22 pm](https://cloud.githubusercontent.com/assets/56477/13559246/cdbc55de-e3c6-11e5-939b-85df08613c68.png)
