### ISSUE TITLE
Geodata downloads have misleading precision

### ISSUE THREAD

**Issue by vielmetti** [censusreporter/censusreporter#125]
To repeat:

```
curl -s 'http://api.censusreporter.org/1.0/geo/show/tiger2013?geo_ids=86000US48104'
```

which returns a big string of JSON data of coordinates. Some of those coordinates have been rounded in a funny way, e.g.

[-83.743816, 42.302535999999996],

is one dot in the polygon, which should probably be

[-83.743816, 42.302536]

The other advantage of rounding to 6 decimal digits of precision is that the data returned is more compact.

**Comment by JoeGermuska** [comment]
Fair enough, but this ultimately comes down to a stack of libraries which use FP math instead of fixed precision math. 

I'd need a lot of persuading of benefits beyond shaving a few bytes off the data to add the complexity it would take to deliver 6-decimal precision.

**Comment by JoeGermuska** [comment]
well whadda I know? thanks @iandees

**Comment by iandees** [comment]
The downloaded data will still have weird precision, but that's because OGR puts all numbers into a "real" floating point type that is the least common denominator between all the output formats it supports.

**Comment by vielmetti** [comment]
Super! First test passes. Thanks @iandees
