### ISSUE TITLE
DD tags have a lot of excess padding in topical help pages.

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#132]
eg on http://censusreporter.org/topics/table-codes/#table-subjects and various other places in topical help

![google chrome](https://cloud.githubusercontent.com/assets/46313/9417199/cdf52dee-480f-11e5-9818-64057610d10b.png)

**Comment by ryanpitts** [comment]
Tightening this up for the dl-horizontals

![screen shot 2015-09-05 at 11 09 42 am](https://cloud.githubusercontent.com/assets/56477/9700632/a064f2b4-53be-11e5-8f8c-11b7c78157f2.png)
