### ISSUE TITLE
Place search max-suggestions makes some MSAs unfindable

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#135]
A UserVoice ticket indicated that all of the following MSAs cannot be found in the profile search tool because there are too many matches at higher summary level priorities, preventing the MSA matches from ever being shown.

14460 Boston-Cambridge-Newton, MA-NH
17460 Cleveland-Elyria, OH
18140 Columbus, OH
19100 Dallas-Fort Worth-Arlington, TX 
19740 Denver-Aurora-Lakewood, CO
26900 Indianapolis-Carmel-Anderson, IN
31540 Madison, WI
37980 Philadelphia-Camden-Wilmington, PA-NJ-DE-MD
38900 Portland-Vancouver-Hillsboro, OR-WA
40380 Rochester, NY
41180 St. Louis, MO-IL
45780 Toledo, OH
47260 Virginia Beach-Norfolk-Newport News, VA-NC
47900 Washington-Arlington-Alexandria, DC-VA-MD-WV

This is a kind of a big problem.

**Comment by ryanpitts** [comment]
Ewww. Regardless of how else we approach fixing this, seems like we ought to bump MSAs higher in the priority queue, right? Higher than county subdivisions sure seems reasonable.

Is that enough to address the issue? Do we need to increase the number of results returned? Those would be the two lightweight options. Anything additional probably requires rethinking the search UI, which maybe you're keen to do :P

**Comment by JoeGermuska** [comment]
you know, I think we should probably just fall back to the elastic search stuff. It's better than nothing, even if we feel like it isn't what it should be.

I'm going to do a little to try to knit them together this weekend.

**Comment by JoeGermuska** [comment]
well, that was pretty easy. 4cb976f (he says, disregarding the cussing about the baroque APIs for Bloodhound and Twitter Typeahead)

**Comment by JoeGermuska** [comment]
Gonna close this for now because there's a working solution and I think there are other things I'd rather work on before filtering geo suggestions, especially since we have the little facet tool on the elastic place search.

**Comment by ryanpitts** [comment]
☕️
