### ISSUE TITLE
Maximum character limit in Apache on URL

### ISSUE THREAD

**Issue by vielmetti** [censusreporter/censusreporter#139]
I'm pulling down geometry from a big list of zip codes all at once. Too big a list, as it turns out, because the file I get back says this:

```
Edwards-MacBook-Air:tmp9 emv$ more merged-zips.13573.geojson
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>414 Request-URI Too Large</title>
</head><body>
<h1>Request-URI Too Large</h1>
<p>The requested URL's length exceeds the capacity
limit for this server.<br />
```

Fortunately, my code had a bug in it that doubled the size of the URL that I was sending around, so I managed to fix this on my own. This is mostly FYI that perhaps a more useful error message might go back somehow, or the limit might be changed, or....

**Comment by JoeGermuska** [comment]
considering the age, and without a test case, i'm just going to close this one out
