### ISSUE TITLE
Handle tabulations with no core table but iterations (e.g B06004)

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#141]
As [pointed out on Twitter](https://twitter.com/burritojustice/status/656316640720621568), Census Reporter errors when going to tabulations which have no "root" table, e.g. http://censusreporter.org/tables/B06004/ doesn't exist, but that's where our tool sends people on an autocomplete. 

Probably, we should just have a redirect to the "first" available table, in this case http://censusreporter.org/tables/B06004A/

**Comment by JoeGermuska** [comment]
Before we close this, a couple of things:

it's small, but I think that when we find that there are iteration tables but not a base, we should redirect to the first iteration (similar to how profile pages redirect when hit with a geoid-but-no-slug). We don't want to give the impression that a URL like http://censusreporter.org/tables/B06004/ is valid, especially if the data on the page is for http://censusreporter.org/tables/B06004A/   

For the list of "other versions" please sort them so that all of the PR tables appear together, and after the US ones?

**Comment by tuchandra** [comment]
Those changes have been made, and are reflected in the branch `no-core-tables`.
