### ISSUE TITLE
Error when querying for table details

### ISSUE THREAD

**Issue by iandees** [censusreporter/censusreporter#149]
A user reported (and we confirmed) that [this page](http://censusreporter.org/tables/B01001/) was returning the following error:

![image](https://cloud.githubusercontent.com/assets/261584/13012218/53dc93b0-d178-11e5-8dc7-d7f7de9af2b0.png)

After poking around a bit I found that the page uses the tabulation endpoint from the API to get the list of tables for the tabulation code. It then queries the API for each of the table IDs inside the tabulation result. In this case, though, the 1-year release has C-prefixed tables and the 5-year release does not. Since the default ACS for querying table details is the 5-year, the API returns a 404 and the Django app gives up and returns the error.

The temporary workaround I put in place was to skip over the tables that get a 404 from the API. In this case, that means the C-prefix tables aren't going to be shown on the frontend.

I think the desired behavior would be to pick the correct release for the table and query the API with that release rather than leave the default. Another option might be to change the API to query all releases for the table (and return release information with the result).

**Comment by JoeGermuska** [comment]
I no longer see that error. Maybe we engineered this away?
