### ISSUE TITLE
Grammar bug

### ISSUE THREAD

**Issue by brentajones** [censusreporter/censusreporter#150]
On a profile page, the links under charts initially say "show data". When clicked, they change to "hide **the** data" — and simultaneously, other charts on the same line switch to say "show **the** data". When clicked again, to collapse the charts, they revert to "show **the** data". 

This could easily be made consistent by changing the [initial label](https://github.com/censusreporter/censusreporter/blob/08c9e6e1b23c1641a3235dd7c35f2ea35f477033/censusreporter/apps/census/static/js/charts.js#L726-L730) to say "Show the data". Alternately, changing the [clicked label](https://github.com/censusreporter/censusreporter/blob/08c9e6e1b23c1641a3235dd7c35f2ea35f477033/censusreporter/apps/census/static/js/charts.js#L850-L911) to say "Hide data".

(I realize this is super-nitpicky, but if someone's looking for a cheap win…they don't come much cheaper than this).

**Comment by ryanpitts** [comment]
ugh, can't believe I missed this. I appreciate the nitpick, this is the kind of stuff that bugs me too.
