### ISSUE TITLE
Deliberate ordering for facets in full text search.

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#170]
We should be intentional about ordering. For profiles, we should either be alphabetic or use the ordering that `/locate/` uses.  @ryanpitts suggests not alphabetic because, for example, it would spread out the school districts.

For topics, I think alphabetic is correct.

**Comment by Joonpark13** [comment]
The filters are now ordered by sumlevel for sumlevel names and alphabetically for topics.
