### ISSUE TITLE
Reconsider tabs in full-text search

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#171]
What is the value of the 'all' tab? Does anyone really want both types of results in one list?

The best value is if it makes it easier for the person to find what they're looking for -- but if all profile results come before all topic/table results, that doesn't really pay off.  If we shuffled them together it might help.  

Having all profile together and first also makes clicking from 'all' to 'profile' look like nothing changes, which isn't ideal.

My only concern is if people are searching for topics and get places-and-topics and don't see the topics tab, that would be frustrating. But if topic results are "below the fold" and people can't see them, that's not much better.

**Comment by Joonpark13** [comment]
After some discussion it seems that the consensus is that there wouldn't really be a time when people are looking for a combination of both types of pages. We'll get rid of the "all" tab.
