### ISSUE TITLE
Throttle tile requests in profile map for certain sumlevel/zoom levels

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#18]
There are no doubt certain combinations of summary level and map zoom level where the geometries are unintelligible.

Although, experimenting with zooming, thinly populated areas have some giant block groups, even just DeKalb county at say zoom level 8.  Then again, in the JS console, we can also see that some of the paths we return at that zoom level have NaNs in them, so...

perhaps we should determine, at least for smaller sumlevels, some zoom threshold below which we won't bother asking for geotiles?

(somewhat related to #13)

**Comment by iandees** [comment]
We should probably prevent zooming based on overlay sumlevel (more dense sumlevels should prevent zooming out too far). I don't think there's much we can do to simplify the data more than we already do.

**Comment by JoeGermuska** [comment]
I think rather than prevent zooming we can simply disable the navigable layer at some zoom level which appropriate to the summary level.

**Comment by JoeGermuska** [comment]
This doesn't seem to be important, based on age.
