### ISSUE TITLE
Include locations as part of search results

### ISSUE THREAD

**Issue by Joonpark13** [censusreporter/censusreporter#180]
Offshoot of Issue #179: since locations are being suggested by the auto-suggest, they should also be displayed as results on the results page. It feels very strange for a user to see a bunch of locations as autosuggested options but then see "No results found" when they hit "Don't see what you're looking for?"

**Comment by Joonpark13** [comment]
Commit ef753c5 adds this functionality. Currently, the subtext of the address is the lat/long coordinates. Would something else better fill that space?

**Comment by JoeGermuska** [comment]
Unfortunately I won't be in a position to look at this until I'm back from this trip. The lat/lng doesn't seem appropriate, and could even be offputting to less savvy users. Maybe "Address Search"? or just no subtext?

**Comment by JoeGermuska** [comment]
Sorry, I was imagining the suggestions, not the in page results. I think just no subtext. If it looks different from everything else, well... It is! But it'll be easier to think about when I  can see it in action

**Comment by Joonpark13** [comment]
Right now the subtext is just "Location" - I think that's the best way to do it. We can talk about this more when you get back.

**Comment by Joonpark13** [comment]
Clicking on the location result takes you to a page where the label is the search query string, not the actual search result name. Working on a fix.
