### ISSUE TITLE
Chart embed inconsistent with page

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#182]
[On UserVoice, someone reported](https://censusreporter.uservoice.com/admin/tickets/210/?q=assignee%3Ame+status%3Aopen) that the text in the center of the chart is inconsistent with the default display on a profile page.  I verified. Here are screenshots:

**My test**
![image](https://cloud.githubusercontent.com/assets/46313/17375964/0384b4cc-5979-11e6-8084-656f79ea6cec.png)

**From the [Chicago Metro profile page](http://censusreporter.org/profiles/31000US16980-chicago-joliet-naperville-il-in-wi-metro-area/)**
![image](https://cloud.githubusercontent.com/assets/46313/17375980/13e674ea-5979-11e6-8801-4022d8e0a682.png)

**From the [32801 profile page](http://censusreporter.org/profiles/86000US32801-32801/)**
![image](https://cloud.githubusercontent.com/assets/46313/17376010/37ef4bb4-5979-11e6-971d-0813f5b120cc.png)

**Comment by ryanpitts** [comment]
Huh! So yeah I _think_ that one's probably not a super complicated fix. IIRC the chart javascript defaults to highlighting the first category in a given donut chart. This can be overridden, though, and on the profile pages we're passing in a param that says to highlight the largest category instead. See `data-initial-sort="-value"` here:

    <div class="column-quarter" id="chart-pie-demographics-age-distribution_by_category" data-stat-type="percentage" data-chart-title="Population by age category" data-initial-sort="-value"></div>

It looks like the embed code _is_ passing the exact same sort value (there's an `&initialSort=-value` param in the querystring here):

    <iframe id="cr-embed-86000US32801-demographics-age-distribution_by_category" class="census-reporter-embed" src="https://s3.amazonaws.com/embed.censusreporter.org/1.0/iframe.html?geoID=86000US32801&chartDataID=demographics-age-distribution_by_category&releaseID=ACS_2014_5-year&chartType=pie&chartHeight=200&chartQualifier=&chartTitle=Population+by+age+category&initialSort=-value&statType=percentage" frameborder="0" width="100%" height="300" style="margin: 1em; max-width: 300px;"></iframe>
<script src="https://s3.amazonaws.com/embed.censusreporter.org/1.0/js/embed.chart.make.js"></script>

So for some reason the embed chart javascript is not honoring that param?

**Comment by ryanpitts** [comment]
So I think this is the bug: https://github.com/censusreporter/censusreporter/blob/master/censusreporter/apps/census/static/js/embed.chart.frame.js#L67

The embed querystring is passing `&initialSort=-value`, but that line in the embed javascript is expecting a param called `chartInitialSort`. If we change that line in `embed.chart.frame.js` to:

    chartInitialSort: embedFrame.params.initialSort,

I bet it will fix the problem. (Note that this change still has to be copied manually to the S3 bucket where we serve the embed stuff from, there are some quirks around auto-deployment there so it's still a manual process.)

**Comment by Joonpark13** [comment]
@ryanpitts changing the value of `chartInitialSort` to `embedFrame.params.initialSort` doesn't seem to have worked. Any other ideas?

**Comment by ryanpitts** [comment]
unless my local tests just now are way off, I think this does work -- I'm guessing the issue is that the `embed.chart.frame.js` that's in the S3 bucket (where all the embeds get served from) is _not_ automatically synced with the version of the file in the repo.

It's a pain in the butt, but there's actually a decent reason those embed files aren't synced automatically -- there are a couple of hard-coded asset paths that need to be set a certain way in S3. There's probably a clever way of working around that, but I didn't find one.

**Comment by ryanpitts** [comment]
Sorry, looking back I realize I wasn't very clear in guessing why that change didn't look like it worked for you!

The embed code serves up everything from our S3 bucket -- data, css, js, iframe, everything -- which makes testing changes to that code a little awkward. You have to take code like:

    <iframe id="cr-embed-31000US16980-demographics-age-distribution_by_category" class="census-reporter-embed" src="https://s3.amazonaws.com/embed.censusreporter.org/1.0/iframe.html?geoID=31000US16980&chartDataID=demographics-age-distribution_by_category&releaseID=ACS_2014_1-year&chartType=pie&chartHeight=200&chartQualifier=&chartTitle=Population+by+age+category&initialSort=-value&statType=percentage" frameborder="0" width="100%" height="300" style="margin: 1em; max-width: 300px;"></iframe><script src="https://s3.amazonaws.com/embed.censusreporter.org/1.0/js/embed.chart.make.js"></script>

and change the `iframe` src and the `script` src to a local reference:

    <iframe id="cr-embed-31000US16980-demographics-age-distribution_by_category" class="census-reporter-embed" src="iframe.html?geoID=31000US16980&chartDataID=demographics-age-distribution_by_category&releaseID=ACS_2014_1-year&chartType=pie&chartHeight=200&chartQualifier=&chartTitle=Population+by+age+category&initialSort=-value&statType=percentage" frameborder="0" width="100%" height="300" style="margin: 1em; max-width: 300px;"></iframe><script src="js/embed.chart.make.js"></script>```

And then drop it into https://github.com/censusreporter/censusreporter/blob/master/censusreporter/apps/census/static/embed.html, run a local server, and test at `http://127.0.0.1:8000/static/embed.html`. Then you're looking at an embed that is entirely drawing on local versions of the `frame` and `make` js, and the `iframe.html`. Like 99% of the time, those are the three relevant files here. And I often find that I need to hard-refresh to be sure I'm drawing only the freshest versions of those local files. (I'm sure there are other workflows that would also work for testing, but this is one that's tried and true.)

Once you've got that local embed working like you want, you would commit any changes to `iframe.html`, `embed.chart.frame.js`, and `embed.chart.make.js`, and push to the repo so we have everything reflected here. To actually implement _for end users_, though, you need to edit those files inside the S3 bucket at `embed.censusreporter.org/1.0/` (changing only the lines that you edited).

It's weird and two steps and not the _most_ efficient, but like I mentioned above, there's some asset paths that need to be set certain ways in the files in S3 (hence the note about only editing the lines that changed in your git commit). And keeping those files separate does also have the side effect of letting us develope locally and deploy for testing without risking breaking all the embeds that people have published.

So, long-winded I know. But my guess is that when you tried this fix, the embed code might have still been calling out to the S3 version of the js, rather than the file you edited. Would be great to verify if the commit I just pushed (and then made the corresponding edit in S3) is working now though.
