### ISSUE TITLE
Marital status by sex table missing primary x axis labels

### ISSUE THREAD

**Issue by longhotsummer** [censusreporter/censusreporter#187]
The chart (eg at http://censusreporter.org/profiles/16000US5363000-seattle-wa/#marital-status ) shows male/female breakdown, but is missing primary x axis labels for the marriage category.

For which grouping should the totals be 100%?

![seattle wa - profile data - census reporter 2016-08-16 09-26-10](https://cloud.githubusercontent.com/assets/4178542/17691221/8f628dd8-6393-11e6-936b-38f1330400cf.png)

**Comment by JoeGermuska** [comment]
as of today, this is not reproducible:

![image](https://user-images.githubusercontent.com/46313/50655386-96e90080-0f55-11e9-8314-88216258e2e6.png)
