### ISSUE TITLE
for geocoder, filter out non-US results

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#188]
Results from the Mapbox geocoder include a `context` array of "parent" geographies. If none of the "parents" are US or Puerto Rico, the results should be filtered out from the autosuggest and the results displayed on `/search-results/`

It would probably be safe to use the mapbox IDs and drop any results which don't have any context objects with ID of either `country.12862386939497690` (US) or `country.12076878448498950` (PR)

**Comment by iandees** [comment]
I think you can tell it what countries to limit results to when querying? /cc @MikelMaron

**Comment by JoeGermuska** [comment]
I didn't see it at https://www.mapbox.com/api-documentation/#search-for-places -- you could do a bounding box, but a whole-US bbox is too big.

Assuming that we do need to check the contexts, It might be worth checking the context for the "Island Areas" -- Virgin Islands, Guam, Northern Marianas and American Samoa -- to make sure that they don't come back with US as one of their context geographies -- but since PR doesn't have that, I'm guessing they don't.

**Comment by mikelmaron** [comment]
you can limit the request, pass in a list of country codes. arguments documented here https://www.mapbox.com/api-documentation/#request-format
