### ISSUE TITLE
Problems with apostrophes and periods in place names?

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#19]
A UserVoice support ticket revealed that our current place lookup mechanism doesn't handle names like "O'Fallon, MO"

This happens in all of the place lookup fields I've tried.

**Comment by Caged** [comment]
I was looking for a bug to tackle and took a peek at this one.  This appears to be an issue at the census-api level.  You can reproduce the behavior by loading [the API URL](http://api.censusreporter.org/1.0/geo/search?q=O%27Fallon%2C%20MO&sumlevs=010,020,030,040,050,060,160,250,310,500,610,620,860,950,960,970) directly.   I wasn't able to get the census-api side of things running locally, but it appears that [these regexs](https://github.com/censusreporter/census-api/blob/master/census_extractomatic/api.py#L1405-L1406) might need some adjustments.  In addition to apostrophes and periods, dashes are also problematic.  For example, if you paste in "Miami-Dade,"  the resultset is empty.

**Comment by JoeGermuska** [comment]
sorry, meant to reply to this days ago, but it got lost in the tab forest...

Care to give us some more info (here or elsewhere) on the issues in getting the API running locally?

**Comment by JoeGermuska** [comment]
Verified that "O'Fallon" is still an issue.

The other thing, about pasting "miami-dade" into the search box, currently functions correctly

**Comment by tuchandra** [comment]
Our (@Joonpark13 and my) implementation of full text search now handles these. Dashes and periods were not a problem to begin with, but apostrophes still were. We discovered that, when the search index was built, apostrophes were treated as delimiters between words (i.e., spaces); a change to api.py to do the same solves the issue. 

Test cases: `o'fallon`, `ft. lauderdale`, `st. louis`, `miami-dade`.
