### ISSUE TITLE
Lorem ipsum type in embed modal

### ISSUE THREAD

**Issue by critmcdonald** [censusreporter/censusreporter#199]
I was browsing around on the Census Reporter and noticed a paragraph at the bottom of the embed modal for charts. Thought you might want to know.

![screen shot 2016-09-24 at 4 03 32 pm](https://cloud.githubusercontent.com/assets/4553750/18811353/6da8d744-8272-11e6-9498-1701e9821325.png)

**Comment by ryanpitts** [comment]
@critmcdonald ahhh, the lorem ipsum is actually there on purpose! It provides some example text so you can see how your chart alignment choice will look next to text on your page.

That default view sure doesn't make that obvious though, and I can absolutely see why you filed a ticket. I'll add a sentence at the beginning of the lorem ipsum there to provide some context. Thank you for pointing this out!

**Comment by critmcdonald** [comment]
Thanks @ryanpitts, that make total sense to me now. #im_a_dork

**Comment by ryanpitts** [comment]
Nope, not a dork at all. It's really easy for us to make assumptions based on the context that _we_ have when we add new features, so it's super helpful to hear from people who are looking at things with fresh eyes. Can totally see how this would have been confusing.

**Comment by ryanpitts** [comment]
Closed with https://github.com/censusreporter/censusreporter/commit/b54e122f8c36e5f7c3aef6af31b0c0f99222e8bf
