### ISSUE TITLE
No data on site or API for territories.

### ISSUE THREAD

**Issue by JoeNVF** [censusreporter/censusreporter#210]
PR is available, but Guam, American Samoa, and more are not available at all.

Is it possible to add these to the site and/or API.

While I'd like to be able to see everything, my primary would be GU and AS via API.

**Comment by JoeGermuska** [comment]
Only Puerto Rico is included in the American Community Survey (ACS), and Census Reporter only serves data from the ACS. Unfortunately, we can't offer data for the [Island Areas](https://www.census.gov/history/www/programs/geography/island_areas.html).
