### ISSUE TITLE
B05006: Incorrect indent level for "Denmark"

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#214]
I found this looking at [this map](https://censusreporter.org/data/map/?table=B05006&geo_ids=140|31000US36740#column|B05006139,sumlev|140) but then realized I was looking past it on the "table" view -- Denmark has too low of an indent level. 

![image](https://cloud.githubusercontent.com/assets/46313/22472985/e5fd46e6-e79c-11e6-9a91-2677bda2b7d8.png)

![image](https://cloud.githubusercontent.com/assets/46313/22472884/8b697fd8-e79c-11e6-9193-1a57e3da404c.png)

**Comment by iandees** [comment]
💪  CENSUSSS!!

**Comment by logantpowell** [comment]
Is this something on our end (Census) that needs attention?

**Comment by JoeGermuska** [comment]
@logantpowell it's that ol' metadata question. @iandees did this come from an Excel file again this year?

**Comment by logantpowell** [comment]
@JoeGermuska ugh... that ol' thing...

**Comment by iandees** [comment]
I've only been able to find the indent/column hierarchy information by inspecting the formatting of the [table shells file](http://www2.census.gov/programs-surveys/acs/summary_file/2015/documentation/user_tools/ACS2015_Table_Shells.xlsx). It looks like the row with Denmark in that .xlsx (row 1902) has a formatting error in column B that probably screws up our conversion/hierarchy detector.

**Comment by logantpowell** [comment]
Ah, I see... the "line" value is text (instead of numeric) format. Should I report it or...

**Comment by iandees** [comment]
Let's see if the wider problem is solved when I fix that formatting problem locally. I'll try that later tonight.

**Comment by JoeGermuska** [comment]
de facto a duplicate of #226
