### ISSUE TITLE
Older data not available

### ISSUE THREAD

**Issue by milafrerichs** [censusreporter/censusreporter#216]
Hi,

first of thank you for Censusreporter. It is very helpful.

But, I ran into a problem trying to find older data. 
I tried the 2012 data specified here:
https://github.com/censusreporter/censusreporter#show-data
`https://api.censusreporter.org/1.0/data/show/acs2012_5yr?table_ids=B01001&geo_ids=16000US5367000`
and I get a `404 not found` `The acs2012_5yr release isn't supported.`

I would love to donwload older data.

Thanks.

**Comment by iandees** [comment]
At this time we don't have the resources to maintain older data in our database. The query you gave is an example that probably should be updated. If you'd like to query older data you can use [our database extracts](http://censusreporter.tumblr.com/post/73727555158/easier-access-to-acs-data) or the [Census API](http://www.census.gov/developers/).
