### ISSUE TITLE
Search shows obsolete tables

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#222]
From [the 2015-5 year table changes](https://www.census.gov/programs-surveys/acs/technical-documentation/table-and-geography-changes/2015/5-year.html)
> Six new Detailed Tables (B02014, B02015, B02016, B02017, B02018 and B02019) published for racial groups, which include additional detailed information regarding American Indian and Alaska Natives (AIAN), Asians, and Native Hawaiian and other Pacific Islanders (NHPI). These new tables will replace Detailed Tables B02005, B02006, B02007. 
> Detailed Tables B02005, B02006 and B02007 have been deleted. Detailed Tables B02014, B02015, B02016, B02017, B02018 and B02019 are available alternatives. 

But those deleted tables still crop up.

@Joonpark13 I wonder if you could take a look at this at some point?

**Comment by Joonpark13** [comment]
I actually can't seem to find those three deleted tables through any search... where specifically were you finding them?

**Comment by Joonpark13** [comment]
@JoeGermuska They seem to appear on the sitemaps

**Comment by JoeGermuska** [comment]
Added note to update process about regenerating the sitemaps in censusreporter/census-api@aa51541
