### ISSUE TITLE
Florida Congressional boundaries

### ISSUE THREAD

**Issue by adelaide01** [censusreporter/censusreporter#236]
The downloaded version of the shapefiles as well as the KML format are old, before redistricting. 
However, the ones that are displayed are correct: https://censusreporter.org/data/map/?table=B00001&geo_ids=04000US12,050|04000US12,500|04000US12&primary_geo_id=04000US12#column|B00001001,sumlev|500

So, the fix is to replace the download version with the newer boundaries.

**Comment by JoeGermuska** [comment]
Verified:  from a fresh download from the page above:
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/46313/48375620-224cc080-e68e-11e8-9808-dc2cdeea58d3.png">

From the page linked above:
![image](https://user-images.githubusercontent.com/46313/48375634-2d9fec00-e68e-11e8-8bdd-f56ee68ac3f1.png)

**Comment by JoeGermuska** [comment]
downloaded today: 
![image](https://user-images.githubusercontent.com/46313/50662056-b63e5880-0f6a-11e9-95b4-15f1227a1dda.png)

looks like a better match.  I'm assuming this was resolved as part of the most recent data update.

**Comment by adelaide01** [comment]
Much appreciated. All of Florida thanks you!
