### ISSUE TITLE
/data/ view doesn't honor release

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#239]
Turns out that the API URL has `latest` hardcoded into it which is probably why adding `release` to the URL doesn't get data for a different release

https://github.com/censusreporter/censusreporter/blob/master/censusreporter/apps/census/views.py/#L466-L480

see for example https://censusreporter.org/data/table/?table=C02015&geo_ids=16000US1770122&primary_geo_id=16000US1770122&release=acs2016_5yr

**Comment by ryanpitts** [comment]
Is it supposed to honor the release? For some reason I thought we took that out because we weren't sure we'd be keeping all past data around.

**Comment by JoeGermuska** [comment]
We don't plan to keep all past data around -- however, there's the possibility that someone intentionally wants 5-year data when our method determines that they should see 1-year data. This came up today in [UserVoice #452](https://censusreporter.uservoice.com/admin/tickets/452/) (although technically that person asked for the previous 5-year, not the current.)

Still, I think it would be worth fixing, especially because it seems related to #213 .

I looked at this a bit today; it's a little more tangled than I like, so I think I'll save it for the students to work on, but here are some notes:

From a Django perspective, this starts at [`views.DataView`](https://github.com/censusreporter/censusreporter/blob/master/censusreporter/apps/census/views.py/#L442-L478), which needs to see the `release` parameter -- it also needs to deal with the possibility that the release parameter isn't valid, since the parameter is used to look up a dictionary which provides human-readable information in the citation, if nothing else.  

Data that the Django view puts into context gets passed through to the template, where it's [used to instantiate a `Comparison` JS object](https://github.com/censusreporter/censusreporter/blob/master/censusreporter/apps/census/templates/data/_base_data.html/#L54-L66).  The release would need to be passed in there, and then used in the Comparison (defined in [comparisons.js](https://github.com/censusreporter/censusreporter/blob/master/censusreporter/apps/census/static/js/comparisons.js) ) to change the data call, etc.

**Comment by JoeGermuska** [comment]
This came up again on UserVoice: https://censusreporter.uservoice.com/forums/224412-general/suggestions/38019613-add-acs-5-year-estimates

**Comment by JoeGermuska** [comment]
this came up again today in UserVoice. Two different calls to the API, both specifying "latest" and both providing the same list of GeoIDs, make different choices about which release to use:

[This call](https://api.censusreporter.org/1.0/data/show/latest?table_ids=B03002&geo_ids=05000US42101%2C05000US42045%2C05000US42091%2C05000US42017%2C05000US10003%2C05000US42029%2C05000US34033%2C05000US34015%2C05000US34007%2C05000US34005
), used to populate the data on [this page](https://censusreporter.org/data/table/?table=B03002&geo_ids=05000US42101,05000US42045,05000US42091,05000US42017,05000US10003,05000US42029,05000US34033,05000US34015,05000US34007,05000US34005) uses ACS 2017-5
[This url](https://api.censusreporter.org/1.0/data/download/latest?table_ids=B03002&geo_ids=05000US42101,05000US42045,05000US42091,05000US42017,05000US10003,05000US42029,05000US34033,05000US34015,05000US34007,05000US34005&format=csv
), used to download that "same data" as CSV, actually gets ACS2018-1 year.

The issue does not occur for [this page](https://censusreporter.org/data/table/?table=B01003&geo_ids=050%7C04000US17&primary_geo_id=04000US17#), which shows and downloads ACS2017-5 year data.

**Comment by JoeGermuska** [comment]
[Another UserVoice case](https://censusreporter.uservoice.com/admin/tickets/775/?q=assignee%3Ame+status%3Aopen).
