### ISSUE TITLE
Rebuild EBS snapshots

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#24]
As we discussed, they're out of date. Also, would solve censusreporter/census-postgres-scripts#7

**Comment by JoeGermuska** [comment]
@iandees this is done right?

**Comment by iandees** [comment]
I haven't published EBS snapshots because the SQL dumps are quite a bit easier to use and maintain. We have snapshots that I take as part of building an AMI for our internal use and those are fairly up to date.

**Comment by JoeGermuska** [comment]
OK. I think I was confusing it with the snapshots referenced in http://censusreporter.tumblr.com/post/55886690087/using-census-data-in-postgresql

If you want to close this, please do. In general, we have a lot of clutter in issues, it would be nice to weed and also to add tags for priority, easiness ,etc.

**Comment by iandees** [comment]
I'm going to close this. Let me know if we get anyone looking for the EBS snapshots again.
