### ISSUE TITLE
Tiger 2017 geocontainment has no tract (140) children of places (160)

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#248]
Something must have gone awry in the data load. This leads to nothing happening when someone is looking at a data grid and selects "divide [place name] into census tracts"

```sql
select count(*) from tiger2017.census_geo_containment 
  where substr(parent_geoid,1,3) = '160' 
  and substr(child_geoid,1,3) = '140';
 count 
-------
     0
(1 row)

select count(*) from tiger2016.census_geo_containment 
  where substr(parent_geoid,1,3) = '160' 
  and substr(child_geoid,1,3) = '140';

 count 
-------
 96301
(1 row)
```

**Comment by JoeGermuska** [comment]
@iandees I extracted the following SQL from [`census-postgres-scripts/13_index_tiger_2017.sql`](https://github.com/censusreporter/census-postgres-scripts/blob/master/13_index_tiger_2017.sql/#L826-L841) and executed it on my local mirror of the `tiger2017` database.


```sql
-- Tracts (140) in Places (160)
INSERT INTO tiger2017.census_geo_containment (
    SELECT
        '14000US' || tract.geoid AS child_geoid,
        '16000US' || place.geoid AS parent_geoid,
        ST_Area(ST_Intersection(tract.geom,place.geom))/ST_Area(tract.geom)*100 as percent_covered
    FROM tiger2017.tract
    JOIN tiger2017.place ON ST_Intersects(tract.geom, place.geom)
    WHERE
        ST_IsValid(tract.geom) AND
        ST_Area(ST_Intersection(tract.geom,place.geom))/ST_Area(tract.geom) > 0
    ORDER BY
        child_geoid ASC,
        ST_Area(ST_Intersection(tract.geom,place.geom)) DESC
);

```

The first time I ran it, it seemed to hang for an exceedingly long time. Maybe I had some connection problem, but I can't think what it was.  I ended up forgetting about it and closing my laptop, cutting off the session.  When I resumed, the same command immediately returned the following:

```ERROR:  Error performing intersection: TopologyException: Input geom 1 is invalid: Holes are nested at or near point -84.08246299999999 35.893129000000002 at -84.08246299999999 35.893129000000002
```

Adding another `ST_IsValid` operation on the other geometry has the code executing, issuing repeated warnings about that specific "nested holes" problem. It continues to run as I submit this comment.

Ideas for how to address this? Again, the user impact of this is that when people try to divide places into tracts, they get an empty result set, which isn't correct.

**Comment by JoeGermuska** [comment]
Just because I was curious, I looked at that on Census Reporter:
https://censusreporter.org/locate/?lat=35.893129&lng=-84.0824629&address=801%20Fairway%20Oaks%20Lane,%20Knoxville,%20Tennessee%2037922

![image](https://user-images.githubusercontent.com/46313/51194413-9f73fc00-18b0-11e9-8524-433de9af2516.png)

![image](https://user-images.githubusercontent.com/46313/51194476-bfa3bb00-18b0-11e9-8751-062a205edbe4.png)

so that's obviously the problem.

2016 Census tracts "in" Knoxville:

```sql
select count(*) from tiger2016.census_geo_containment 
  where child_geoid like '14000US%' 
  and parent_geoid = '16000US4740000';
 count 
-------
    87
(1 row)

```

still doesn't add up. probably shouldn't expect it to, but I was just curious...

**Comment by JoeGermuska** [comment]
another slow-running curiosity query:

```sql

select full_geoid, simple_name, st_isvalidreason(geom) 
  from tiger2017.census_name_lookup 
  where ST_IsValid(geom) = false;
```

full_geoid   |          simple_name          |                   st_isvalidreason                    
----------------|-------------------------------|-------------------------------------------------------
 40000US75340   | Riverside--San Bernardino, CA | Hole lies outside shell[-117.226055 33.837282]
 97000US1302190 | Floyd County School District  | Holes are nested[-85.237741 34.291927]
 97000US1302430 | Gordon County School District | Holes are nested[-84.910317 34.49755]
 97000US1302610 | Hall County School District   | Holes are nested[-83.83426 34.277867]
 97000US1301290 | Cobb County School District   | Holes are nested[-84.504092 33.923422]
 01000US        | United States                 | Self-intersection[-97.5782881555699 25.9423064369684]
 16000US4740000 | Knoxville                     | Holes are nested[-84.082463 35.893129]

**Comment by iandees** [comment]
I ran `ST_MakeValid()` on the busted `place` geometry:

```sql
update tiger2017.place set geom=st_makevalid(geom) where st_isvalid(geom) is false;
```

Then the select (that goes into the insert) worked:

```sql
SELECT
    '14000US' || tract.geoid AS child_geoid,
    '16000US' || place.geoid AS parent_geoid,
    ST_Area(ST_Intersection(tract.geom,place.geom))/ST_Area(tract.geom)*100 as percent_covered
FROM tiger2017.tract
JOIN tiger2017.place ON ST_Intersects(tract.geom, place.geom)
WHERE
    ST_IsValid(tract.geom) AND ST_IsValid(place.geom) AND
    ST_Area(ST_Intersection(tract.geom,place.geom))/ST_Area(tract.geom) > 0 AND
    place.geoid = '4740000'
ORDER BY
    child_geoid ASC,
    ST_Area(ST_Intersection(tract.geom,place.geom)) DESC;
```

and returned 87 rows.

I'm gong to run the insert now to update the geo containment table.

**Comment by iandees** [comment]
And it's done. 96,098 new containment pairs added.

**Comment by JoeGermuska** [comment]
Thanks, @iandees !
