### ISSUE TITLE
State Senate Disitrict 20 New York 

### ISSUE THREAD

**Issue by statesnate20** [censusreporter/censusreporter#255]
Greetings all. Compliments on a informative website.

I was wondering if there was a link like this for State Senate District 20 for NY State.

https://censusreporter.org/profiles/61000US36018-state-senate-district-18-ny/

Keep up the good work!

**Comment by iandees** [comment]
Thanks for the feedback! The page you're looking for can be found by searching for "state senate district 20" in the search box. Here's the link: https://censusreporter.org/profiles/61000US36020-state-senate-district-20-ny/

**Comment by statesnate20** [comment]
Thanks Ian! Appreciate the prompt feedback and help.

Continued success!

Anderson

Anderson Fils-Aime

Community Liaison/Housing Specialist

Office of NYS Senator Zellnor Y. Myrie

Telephone: (718) 284-4700

Mobile (347) 389-5015

https://www.facebook.com/zellnorfornewyork/

https://twitter.com/zellnor4ny

https://www.instagram.com/zellnor4ny/
