### ISSUE TITLE
ACS 2018 SQL dump in Easier Access

### ISSUE THREAD

**Issue by arredond** [censusreporter/censusreporter#258]
I'm an avid user of your [Easier Access - ACS SQL dumps](https://censusreporter.tumblr.com/post/73727555158/easier-access-to-acs-data) and noticed you recently added a link to the 2018 yearly data, but it seems to be broken (takes me to an XML error page).

Could you please take a look?

Thanks for your awesome work!

**Comment by iandees** [comment]
Please give it another shot. Should be working now.

**Comment by arredond** [comment]
Working perfectly now. Thanks a ton! You rock :)
