### ISSUE TITLE
common simplification between geo shapes (San Pedro Problem)

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#29]
(was https://www.pivotaltracker.com/story/show/72254412)

![illustration of the 'San Pedro Problem'](http://f.cl.ly/items/2x1G1W1p1m2l242q1G19/Image%202014-05-28%20at%203.19.12%20PM.png)
as we can see in  the simplification results for the geojson tile layer and the shape used to fill in the selected profile geography aren't aligned. We should probably get them aligned.

Here's another example ([Bellaire, TX](http://censusreporter.org/profiles/16000US4807300-bellaire-tx/)) where the different simplification levels for the geojson tiles and the json that comes with the census data causes a mess.

**Comment by iandees** [comment]
It looks like the places in particular are getting simplified way too much. Other sumlevs seem OK?

**Comment by iandees** [comment]
I'm happy to help make this happen this time around.

I think we could "upgrade" to [Mapbox Vector Tile format](https://www.mapbox.com/blog/vector-tile-spec-docs/) and not do any simplification at all. This would give us better looking (non-simplified) tiles and skirt around the annoying part of deleting a ton of files on S3. @Joonpark13, if you're interested in map stuff and have the time, I'm happy to work with you to do this.

If there's no time or Joon isn't interested, I can work through fixing/removing simplification on the existing GeoJSON tiles.

**Comment by iandees** [comment]
I think I solved this with https://github.com/censusreporter/census-api/commit/888de00fcf24672bcb6a68a4becd7709d881876e.

**Comment by JoeGermuska** [comment]
This is not actually solved.
<img width="313" alt="image" src="https://user-images.githubusercontent.com/46313/45778843-44dad400-bc1f-11e8-905e-122c0b14142f.png">
see [this Census Tract profile page](https://censusreporter.org/profiles/14000US17031030703-census-tract-30703-cook-il/)

**Comment by iandees** [comment]
I think it is solved but the cases of yuckiness we see are old cached data. Either way we should bust that cache and make sure it's fixed.

**Comment by iandees** [comment]
I reduced the amount of simplification in 8a7c1be and busted the cache manually. That solved this particular case and the few I checked on manually, too. Let me know if it shows up again.

**Comment by JoeGermuska** [comment]
Calling it fixed:

<img width="301" alt="image" src="https://user-images.githubusercontent.com/46313/47460081-575aa700-d7a3-11e8-8d51-b71e97469e5b.png">
