### ISSUE TITLE
GA redistricting

### ISSUE THREAD

**Issue by epicfaace** [censusreporter/censusreporter#318]
The legislative districts are the old boundaries before the 2022 redistricting, for example, see https://censusreporter.org/profiles/61000US13048-state-senate-district-48-ga/ -- though the district shape has changed, see https://ballotpedia.org/Georgia_State_Senate_District_48. How are the boundaries for the districts stored / how can they be changed or updated?

**Comment by JoeGermuska** [comment]
The geographies of the legislative districts are appropriate to the current release of data in Census Reporter.

This year's ACS release should be tabulated to the new geographies. We'll update at that time.

**Comment by epicfaace** [comment]
Thank you!
