### ISSUE TITLE
Handle AIANNH geographies/profile pages correctly.

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#34]
(updated for clarity / passage of time)

As reported by @toolness in #31 we aren't handling profiles for summary level 250 (American Indian Area/Alaska Native Area/Hawaiian Home Land) correctly.

This is because the 'geoid' column in TIGER2014.AIANNH doesn't align with the identifiers in the `acs2014_n.geoheader` column. It's also the case that we aren't handling 252 or 254 correctly, although we luck into handling 251, 256, and 258 correctly because they have their own distinct shapefiles and the geoids align with our expectations.)

Summary level 250 includes both "reservation land" and "off-reservation trust" land. These are specified with the value in `TIGER2014.AIANMH.comptyp` The better match for our geoids is the union of geographies with the same value in `TIGER2012.AIANNH.aiannhce` regardless of the "R" and "T" letters. The number of distinct values for that column matches the number of rows in `acs2014_5yr.geoheader` for sumlevel 250:

``` sql
census=> select count(distinct aiannhce) from tiger2014.aiannh;
 count 
-------
   693
(1 row)

census=> select count(*) from acs2014_5yr.geoheader where sumlevel = 250;
 count 
-------
   693
```

For summary level 252, we want geographies with `AIANHH.comptyp == R`

For summary level 254 we want geographies with `AIANHH.comptyp == T`

``` sql
census=> select comptyp, count(*) from tiger2014.aiannh group by comptyp;
 comptyp | count 
---------+-------
 T       |   219
 R       |   608
(2 rows)

census=> select sumlevel,count(*) from acs2014_5yr.geoheader where sumlevel in (252,254) group by sumlevel;
 sumlevel | count 
----------+-------
      252 |   608
      254 |   219
(2 rows)

```

@iandees do you think it makes sense to create a pseudo-TIGER table reflecting the unions of geographies for summary level 250? For 252 and 254, it may just be a matter of jiggering the formula for referencing a geography...

**Comment by JoeGermuska** [comment]
Just got curious and did some data exploration, so leaving notes: here are the geographies we have in `tiger2014.census_name_lookup`:

 * 230: 12 (Alaska Native Regional Corporation (ANRC))
 * 250: 827 (American Indian Area/Alaska Native Area/Hawaiian Home Land)
 * 251: 473 (American Indian Area-Tribal Subdivision/Remainder)
 * 256: 481 (American Indian Area-Tribal Census Tract)
 * 258: 915 (American Indian Area-Tribal Census Tract-Tribal Block Group)

As noted above, we should also be able to support summary levels 252 and 254

Here are the counts of rows in the actual ACS data for these sumlevels:

```
census=> select sumlevel,count(*) from acs2014_5yr.geoheader 
where sumlevel between 230 and 258 
group by sumlevel order by sumlevel;

 sumlevel | count 
----------+-------
      230 |    12
      250 |   693
      251 |   481
      252 |   608
      254 |   219
      256 |   481
      258 |   915
(8 rows)
```
Here are columns in the `geoheader` table which could be used to establish sensible containment/parentage relationships:

- AIANHH: American Indian Area/Alaska Native Area/ Hawaiian Home Land (Census)
- AITSCE: American Indian Tribal Subdivision (Census)
- AITS: American Indian Tribal Subdivision (FIPS)
- BTTR: Tribal Tract
- BTBG: Tribal Block Group

(but there is only one row with a value in BTTR and none with values in BTBG in `acs2014_5yr.geoheader`)

Here are tables in the `tiger2014` schema which are relevant to native geography:

- anrc (sumlevel 230)
- aiannh (sumlevel 250,252,254 -- see above)
- aits (sumlevel 251)
- ttract (sumlevel 256)
- tbg (sumlevel 258)

Here are the other summary levels in `acs2014_5yr.geoheader` which aren't meant to be mapped, but which can be used for containment relationships.

sumlevel | count | description
-------- | ----- | -----------
260 |   721 | American Indian Area/Alaska Native Area/Hawaiian Home Land-State
269 |  2417 | American Indian Area/Alaska Native Area/Hawaiian Home Land-State-Place/Remainder
270 |  1088 | American Indian Area/Alaska Native Area/Hawaiian Home Land-State-County
290 |   501 | American Indian Area-Tribal Subdivision/Remainder-State
550 | 812 | State-Congressional District-American Indian Area/Alaska Native Area/Hawaiian Home Land

There are several others in the "200 range" of summary levels, but getting down to the tribal tract and block group, it's diminishing returns... We may be better off just specifying parentage in the [code where `census_geo_containment` is built up.](https://github.com/censusreporter/census-postgres-scripts/blob/master/13_index_tiger_2014.sql)

**Comment by tuchandra** [comment]
The three pull requests above (censusreporter/censusreporter#191, censusreporter/census-api#52, and censusreporter/census-postgres-scripts#12) fix this.
