### ISSUE TITLE
Embeddable chloropleth widget

### ISSUE THREAD

**Issue by longhotsummer** [censusreporter/censusreporter#35]
In September we're going to be looking at making an embeddable maps/chloropleth widget, much like the embeddable graphs widget. I was wondering if you'd put any thoughts into this and had any suggestions?

My idea is to follow the same iframe idea as for the embeddable graphs. The URL specifies all the details that the maps URL does today, and we use D3 to draw shapes using the GeoJSON boundaries and colour them in using the table data. It should be even easier than the graph embeds, since the map view is already 90% ajax/client-side.

I'm toying with the idea of not including the underlying map (or making it optional).

Your thoughts would be appreciated.

**Comment by JoeGermuska** [comment]
After all this time, this seems like a de facto `wontfix`
