### ISSUE TITLE
Develop strategy for not switching data out from underneath embedded chart sources

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#52]
The design for embedded charts trusts cached JSON on S3 that also feeds the profile pages. That means when we run data updates, we will change the source data for an embedded chart.

We do have version URLs, we could just increment those for each annual ACS release, or really for each update/subset release, because the "Fallbacks" could change, right?

Is there a better solution? Assigning to @ryanpitts for opinions and design if not full impl.

**Comment by JoeGermuska** [comment]
@ryanpitts didn't you do some work on this? is this still outstanding?

**Comment by ryanpitts** [comment]
Ah, forgot there was an open ticket! I believe this can be closed, although my solution probably should get a little consideration from someone who is not me.
