### ISSUE TITLE
Update census_tabulation_metadata DB table and integrate it into data update process

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#55]
Ian:

I fixed some errors in analyze_metadata.py that hard-coded the assumption that we were working with only 2012 releases.

Can you make sure that our data update process includes editing the [releases_to_analyze](https://github.com/censusreporter/census-table-metadata/blob/master/analyze_metadata.py#L9) value in `analyze_metadata.py`, and that it gets run as part of the process and the table gets updated? (Maybe those latter parts are already happening, since the `unified_metadata.csv` wasn't getting correctly updated -- but I can't find it in the Makefile or elsewhere in the [census-table-metadata](https://github.com/censusreporter/census-table-metadata) repo

**Comment by JoeGermuska** [comment]
The underlying issues this references are fixed. @iandees can you verify that this is integrated into the data update process and close it if so?

**Comment by iandees** [comment]
Yep, it's in the "Update the unified tabulation metadata" section of [this document](https://github.com/censusreporter/census-api/blob/master/DATA_UPDATES.md).
