### ISSUE TITLE
UI support for subtotals within a table

### ISSUE THREAD

**Issue by longhotsummer** [censusreporter/censusreporter#78]
Hey guys. Curious to hear your thoughts around this.

We're adding data for children and want to be able to express things like 'the %age of {13,14,15,...} year olds which are employed'. The current way the table, distribution and map views work is that they calculate percentages by dividing by a single denominator column, which is usually the population for the table. That doesn't work in this case because it's expressing 'the %age of the population who are {13,14,15,...} and work', which isn't quite what we want.

I'd rather not have to significantly adjust the JS or the API to support multiple denominator columns.

An idea is to pre-calculate the underlying values as percentages and force the denominator column value to be 100. We lose actual numbers then, but it should work.

Thoughts welcome. Thanks!

**Comment by JoeGermuska** [comment]
Given the complexity with the sheer number of ACS tables, I'm going to call this `wontfix` -- if we found a case for this, I *think* that the right solution for our codebase would be implementing synthetic tables (#242)
