### ISSUE TITLE
Foreign-born population chart problems

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#87]
(this was sent by @martinburch to our email inbox but belongs here) 

Here’s a screenshot of
http://censusreporter.org/profiles/01000US-united-states/#place-of-birth
![http://censusreporter.org/profiles/01000US-united-states/#place-of-birth](https://cloud.githubusercontent.com/assets/46313/5620091/eb75e564-94ed-11e4-8f7d-1f6a6de9fa5b.png)
)

Look at all those zeros! Something is clearly not right. Also, the crosses denoting a large margin of error should not appear.

The detail table looks OK:
http://censusreporter.org/data/table/?table=B05006&geo_ids=01000US&primary_geo_id=01000US#valueType|estimate

Please look into it.

Thanks,

Martin

**Comment by JoeGermuska** [comment]
Upon [closer review](http://www.census.gov/acs/www/data_documentation/2013_data_product_changes/) this probably has to do with 
```
One line in Detailed Table B05006, "Azores Island," was added.
```

@ryanpitts any chance you can have a look at this?

**Comment by ryanpitts** [comment]
AZORRRRRRRRRRRRRES!

**Comment by JoeGermuska** [comment]
I wonder what the politics behind adding that were, considering that the entire US has only about 25K people from Azores Islands

**Comment by JoeGermuska** [comment]
I just deleted the JSON for the US page and caused it to be reloaded from cache. It still seems to have incorrect values.

http://embed.censusreporter.org.s3.amazonaws.com/1.0/data/profiles/2013/01000US.json

```
curl -I http://embed.censusreporter.org.s3.amazonaws.com/1.0/data/profiles/2013/01000US.json
HTTP/1.1 200 OK
x-amz-id-2: wDlEVCpZlt2DSJoYzxZT2BMo2kAvtfs1jwnzkk4AaU2tFHaAvHC9rTL5OghZ90wETr89AqITcuo=
x-amz-request-id: F63A95B62310663D
Date: Mon, 05 Jan 2015 23:39:31 GMT
Content-Encoding: gzip
Last-Modified: Mon, 05 Jan 2015 23:37:04 GMT
ETag: "eea52c312e17f18bb2614a005f3148d2"
Accept-Ranges: bytes
Content-Type: application/json
Content-Length: 5682
Server: AmazonS3
```

**Comment by JoeGermuska** [comment]
It looks like this has returned, or rather, other ACS changes to B05006 have thrown our computations off, as reported in [UserVoice #459](https://censusreporter.uservoice.com/admin/tickets/459/)

> Data table for Place of birth for foreign-born population (Table B05006) does not match data for Long Beach-Lakewood CCD, Los Angeles County, CA subdivision.

While some values match, the user reported: 
> The numbers for Oceania, Latin America, and North America do not match when viewing the data table versus what is on the profile page. 

* [Long Beach-Lakewood CCD, Los Angeles County, CA Profile Page](https://censusreporter.org/profiles/06000US0603791730-long-beachlakewood-ccd-los-angeles-county-ca/)
* [B05006 as linked from profile page](https://censusreporter.org/data/table/?table=B05006&primary_geo_id=06000US0603791730&geo_ids=06000US0603791730,05000US06037,04000US06)

[This Census page](https://www.census.gov/programs-surveys/acs/news/data-releases/2017/release.html) indicates a new code added, which would be the likely culprit:
>Detailed Table B05006 was modified to include new place of birth code for “St. Martin” (POB=349) under category “Other Caribbean.”

@ryanpitts interested in fixing this? Or should I hand it to one of the students?

**Comment by JoeGermuska** [comment]
Since I was right there looking at the correct column codes, I went ahead and fixed this.

As a consequence, all of the cached profile page JSON for 2017 ACS needs to be deleted. This is in process, but is a slow process (tens of thousands of S3 key deletes).

After the cached JSON is cleared, the `memcached` instance on the server will need to be restarted as well.

**Comment by JoeGermuska** [comment]
Happened again :(

**Comment by ryanpitts** [comment]
new column?

**Comment by JoeGermuska** [comment]
yup, just fixed it, and then remembered that we're not done with the 2018 schema yet, so will deal with that
