### ISSUE TITLE
"Foreign-born" chart misleading?

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#89]
Today I took a look at the profile page foreign-born chart and was momentarily confused by the different scales. 

http://censusreporter.org/profiles/05000US12086-miami-dade-county-fl/#place-of-birth

The 'big number' is percent foreign-born of all population, but the chart numbers are use total foreign-born as the denominator. A hasty reader might accidentally read the chart as percent of total population from each place.

We should add some clarifying text. (we could discuss changing the denominator but for places with small foreign-born pops, iit makes the chart kinda dull.)

**Comment by ryanpitts** [comment]
Hmmm. Does this clarify enough?

![screen shot 2015-01-23 at 4 49 56 pm](https://cloud.githubusercontent.com/assets/56477/5885403/f33bec9e-a320-11e4-86e6-4dd8760ce816.png)

**Comment by ryanpitts** [comment]
or maybe "people who are foreign-born"

**Comment by ryanpitts** [comment]
@JoeGermuska I think I posted this possible fix while you were in mid-ORDCamp, so guessing you missed it. Any thoughts?

**Comment by JoeGermuska** [comment]
seems like a non-issue.
