### ISSUE TITLE
Table page UI obscures "summary level in place" option

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#90]
From a table page (e.g. http://censusreporter.org/tables/B19013/), the placeholder text reads
![image](https://cloud.githubusercontent.com/assets/46313/5818464/6c2af6e8-a07b-11e4-989f-ad27096b8227.png)

This doesn't give any hint that one could, instead, type a summary level. It's true that if someone chose a place then on the data page, there is an option to divide the place into its component summary levels, but that's not super prominent either.

**Comment by ryanpitts** [comment]
"Choose a place or summary level" doesn't hint at that? It does to me, *but* I also already know how that box works.

If not, how do you think we should tweak that?

**Comment by JoeGermuska** [comment]
ah, well i didn't even see "Choose a place or summary level" because "Start typing to pick a place..." is bigger!

I'm ambivalent about how to change it. Part of me thinks we ought to just be more explicit, but I don't want to clutter it up. Maybe just changing the placeholder text?

**Comment by ryanpitts** [comment]
What about something like:

![screen shot 2015-01-23 at 4 35 38 pm](https://cloud.githubusercontent.com/assets/56477/5885231/ee18537c-a31d-11e4-8171-ad2ec27709e4.png)

**Comment by ryanpitts** [comment]
@JoeGermuska another one from while you were in mid-ORDCamp.

**Comment by JoeGermuska** [comment]
Of course, that runs into the hitch that it disappears when people start typing. but since there is already placeholder text, I think this is an improvement.
