### ISSUE TITLE
Strange map flicker on feature hover in Firefox

### ISSUE THREAD

**Issue by ryanpitts** [censusreporter/censusreporter#91]
Noticed while testing https://github.com/censusreporter/censusreporter/pull/86 locally. This doesn't seem to be happening in Chrome or Safari, just in Firefox. And I've never noticed this before now, despite looking at this page MANY MANY times.

The flicker occurs on tiles at the top and to the left of the viewport. You can see it in a more pronounced way if you drag the map down and to the right.

![map_flicker](https://cloud.githubusercontent.com/assets/56477/5885152/823cd32c-a31c-11e4-9ad1-7688670263d6.gif)

Also note the "whiteout" effect when you drag, on the same tiles where you see the dark flickering on hover. Not sure what's causing this, but maybe it's a symptom you've seen before, @JoeGermuska or @iandees?

**Comment by JoeGermuska** [comment]
This seems to be a non-issue with current Firefox (64.0)
